version: '2'
services:
  app:
    image: ghcr.io/revxrsal/docker-springboot:master
    ports:
      - "443:443"
    links:
      - "db:redis"
    volumes:
      - /etc/letsencrypt/live/spleefx.net/:/etc/letsencrypt/live/spleefx.net/
      - data:/root/spleefx-web/data
  db:
    image: "redis:alpine"
    hostname: redis
volumes:
  data: {}
